/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LcarsButton {
        /**
          * The color to use
          * @default 'default'
         */
        "color": string;
    }
}
declare global {
    interface HTMLLcarsButtonElement extends Components.LcarsButton, HTMLStencilElement {
    }
    var HTMLLcarsButtonElement: {
        prototype: HTMLLcarsButtonElement;
        new (): HTMLLcarsButtonElement;
    };
    interface HTMLElementTagNameMap {
        "lcars-button": HTMLLcarsButtonElement;
    }
}
declare namespace LocalJSX {
    interface LcarsButton {
        /**
          * The color to use
          * @default 'default'
         */
        "color"?: string;
    }
    interface IntrinsicElements {
        "lcars-button": LcarsButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lcars-button": LocalJSX.LcarsButton & JSXBase.HTMLAttributes<HTMLLcarsButtonElement>;
        }
    }
}
