'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { LcarsButton as LcarsButtonElement, defineCustomElement as defineLcarsButton } from "@starfleet-technology/lcars/dist/components/lcars-button.js";
import { MyComponent as MyComponentElement, defineCustomElement as defineMyComponent } from "@starfleet-technology/lcars/dist/components/my-component.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type LcarsButtonEvents = NonNullable<unknown>;

export const LcarsButton: StencilReactComponent<LcarsButtonElement, LcarsButtonEvents> = /*@__PURE__*/ createComponent<LcarsButtonElement, LcarsButtonEvents>({
    tagName: 'lcars-button',
    elementClass: LcarsButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as LcarsButtonEvents,
    defineCustomElement: defineLcarsButton
});

export type MyComponentEvents = NonNullable<unknown>;

export const MyComponent: StencilReactComponent<MyComponentElement, MyComponentEvents> = /*@__PURE__*/ createComponent<MyComponentElement, MyComponentEvents>({
    tagName: 'my-component',
    elementClass: MyComponentElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MyComponentEvents,
    defineCustomElement: defineMyComponent
});
